/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cdpda_led_Linuxc */

#ifndef _Included_com_cdpda_led_Linuxc
#define _Included_com_cdpda_led_Linuxc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cdpda_led_Linuxc
 * Method:    openled
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_cdpda_led_Linuxc_openled
  (JNIEnv *, jclass);

/*
 * Class:     com_cdpda_led_Linuxc
 * Method:    closeled
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_cdpda_led_Linuxc_closeled
  (JNIEnv *, jclass);

/*
 * Class:     com_cdpda_led_Linuxc
 * Method:    send
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_cdpda_led_Linuxc_send
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
